apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: auth-service
  description: Authentication service
  tags:
  annotations: 
	backstage.io/source-location: url:backstage.io/source-location: url:https://github.com/effizy/NodeApp/blob/master/catalog-info.yaml
    - javascript
  links:
    - url: https://google.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: guests
