apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: auth-service
  description: Authentication service
  tags:
    - javascript
  links:
    - url: https://google.com
      title: Application UI
      icon: dashboard
      type: application-ui
spec:
  type: service
  lifecycle: production
  owner: guests
