apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-service
  description: Authentication service
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - javascript
  links:
    - url: https://google.com
      title: auth-service-link
      icon: link  # Changed to standard icon
      type: website
spec:
  type: service
  lifecycle: production
  owner: fmb-sre
  providesApis:
    - auth-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: Service API for verifying user authentication status
spec:
  type: openapi
  lifecycle: production
  owner: fmb-sre
  dependsOn:
    - kind: Component  # Fixed syntax
      name: auth-service
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-service
  description: External service for demonstration
  links:
    - url: https://fairmoney.io
      title: external-service-link
      icon: link  # Changed to standard icon
      type: website
spec:
  type: service
  lifecycle: production
  owner: fmb-sre
  consumesApis:
    - auth-api
  